# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#

euler = "../flatiron/euler"

require_relative euler + "/project_euler_power_digit_sum.rb"
require_relative euler + "/oo_multiples.rb"
require_relative euler + "/oo_contains_duplicate.rb"

require 'base64'